language: java
jdk:
  - oraclejdk7
os:
  - linux
sudo: false
notifications:
    on_success: [change] # default: change [always|never|change] 
    on_failure: [change] # default: always [always|never|change] 
